### ISSUE TITLE
logistic regression simulation

### ISSUE THREAD

**Issue by mataddy** [TaddyLab/pose#3]
Repeat the experiment of #2, but on binary response data and fitted with logistic regression.

We can simply threshold the values for y from our current data generating process: map all yb = ifelse(y<0,0,1).

The OOS criteria of interest will be misclassification rate (with p>.5 classed as 1, 0 otherwise) as well as the logistic deviance y*log(p) + (1-y)*log(1-p).

**Comment by LuciusJiang** [comment]
@mataddy 
Sure. I will do the simulation job as soon as possible!

**Comment by LuciusJiang** [comment]
@mataddy 
I hope I can show you the result at the beginning of Sep.

**Comment by mataddy** [comment]
hi @LuciusJiang any updates?

**Comment by LuciusJiang** [comment]
Hi,

I went to your office yesterday afternoon but you were not in office at that time.

I will present you the results next week. How about Thu (Oct. 8) at 4:30 p.m.?

Best,
Hao

**Comment by mataddy** [comment]
hi @LuciusJiang just curious: any updates here?  were you able to get it started running?

**Comment by LuciusJiang** [comment]
Sorry Matt, I caught a really bad cold last weekend.

I am doing the simulation now and will try my best to update the result before tomorrow.

Sorry again!

Best,
Hao

**Comment by mataddy** [comment]
no problem!  don't worry at all.  

also: where exactly is the data from the runs on RCC?  I was just looking for it and couldn't locate.  thanks

**Comment by LuciusJiang** [comment]
What kind of data you want? You mean the simulated one from your paper 5.1?

**Comment by mataddy** [comment]
yep, exactly.  the results you uploaded last week.

**Comment by LuciusJiang** [comment]
All the documents are in the results folder. If you cannot find it, I  can come to your office this afternoon to copy all the results to you with my flash drive.

**Comment by mataddy** [comment]
OK perfect, that works if you are around.  I can't seem to find the correct
folder.  I'm here all day.  cheers, MT

**Comment by LuciusJiang** [comment]
OK, no problem. I will be there in 2 hours.
